Revert "GlassFish 4.1 EJB compatibility fix - cxf imports changed only to necessary packages, fixes following exception in non-spring env: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware"
This reverts commit 93740254dfd7047785b2abb152ae5c584d526268.